Update Developer Guide
AY2324S1-CS2103T-W11-3/tp pull request #10
Opened 2023-10-04 13:57 UTC by shuyangk

The current Developer Guide is modelled after AB3, which does not match the project at hand.

There is a need to change it to suit the current project and contain the relevant information.

Let's update the Developer Guide as necessary to change the required details.

2023-10-04 14:28 UTC, wanghejin requested changes
Only the nit on "++" loll, otherwise lgtm!

2023-10-04 14:28 UTC, wanghejin commented on docs/DeveloperGuide.md
> +(For all use cases below, the **System** is `BandConnect+` and the **Actor** is the `producer`, unless specified otherwise)
Is our app BandConnect++ with two pluses hahaha

2023-10-04 14:28 UTC, wanghejin commented on docs/DeveloperGuide.md
> +    * 3a1. BandConnect+ shows an error message.
lgtm!

2023-10-05 10:16 UTC, tanyyyming approved these changes
There are some places to be edited in a future version, but they are just small changes. Otherwise, LGTM!

2023-10-05 10:16 UTC, tanyyyming commented on docs/DeveloperGuide.md
> +(For all use cases below, the **System** is `BandConnect++` and the **Actor** is the `producer`, unless specified otherwise)
The actor is the "music producer" to be more accurate. This can be modified in a later version.

2023-10-05 10:16 UTC, tanyyyming commented on docs/DeveloperGuide.md
> +
More user stories to be added. I will add some according to our excel sheet after this skeleton is merged.

2023-10-05 10:19 UTC, yytan25 approved these changes
LGTM!

2023-10-05 10:19 UTC, yytan25 commented on docs/DeveloperGuide.md
>  * **Private contact detail**: A contact detail that is not meant to be shared with others
As we add more features to the product, we can add on to this list as well!

2023-10-06 01:38 UTC, wanghejin approved these changes

2023-10-06 01:38 UTC, merged