Update UG Glossary and FAQ
AY2324S1-CS2103T-W11-3/tp pull request #218
Opened 2023-11-12 14:21 UTC by shuyangk

2023-11-12 14:59 UTC, wanghejin requested changes

2023-11-12 14:59 UTC, wanghejin commented on docs/UserGuide.md
> +[Back to Table of Contents](#table-of-contents)
I think it's better if we can put this at the end of every section. Actually I have added the link back to ToC in my other PR that is merged just now haha so I think we probably don't need this right now?

2023-11-12 14:59 UTC, wanghejin commented on docs/UserGuide.md
> +[Back to Table of Contents](#table-of-contents)
Same for this~

2023-11-12 14:59 UTC, wanghejin commented on docs/UserGuide.md
> +**A**: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Addressbook home folder.
LGTM!

2023-11-12 14:59 UTC, wanghejin commented on docs/UserGuide.md
> +| Command   | A command is an instruction given to the application to perform a specific action. For example, `list` is a command that displays all musicians and bands.
I think the glossary part also has merge conflict with my previous PR, but I think yours is better so feel free to replace mine!

2023-11-13 03:19 UTC, merged

2023-11-13 03:20 UTC, tanyyyming commented
All the checks fail because of the EOF newline not present in DG. Not a big issue, will fix on my side when I do the next PR.